### ISSUE TITLE
[MBBSEMU] MBBSEMU - Floating point tests don't print the proper values

### ISSUE THREAD

**Issue by paladine** [enusbaum/MBBSEmu#150]
**Module Information**
MBBSEMU

**Describe the bug**
MBBSEMU FPU tests don't print the proper values. The format is a simple `%f` (float) and `%lf` (double(

**To Reproduce**
Launch MBBSEMU and enter the floating point test option `'S'`
It'll print `Float value is: <random junk float>` and `Double value is: <random junk double>`

**Expected behavior**
Should print values of 3.700000 for both float & double

**Comment by enusbaum** [comment]
Where can I see the source code for the MBBSEMU test module?

The quick test I wrote seemed to work:

![image](https://user-images.githubusercontent.com/1139047/94597316-6c77c480-025b-11eb-94da-8b1aba2c2e8a.png)

But I want to make sure we're comparing apples to apples.

**Comment by enusbaum** [comment]
Looking into it the issue appeared related to specifically `sprintf()`, where `spr()` still worked fine.

![image](https://user-images.githubusercontent.com/1139047/94627547-e2941f80-028b-11eb-85a7-9d145067fd06.png)

Taking a look at the Assembly Generated between the two functions there was one distinct difference between the two functions:

`spr()`:
![image](https://user-images.githubusercontent.com/1139047/94627603-0192b180-028c-11eb-9e42-5c78fbb2ac56.png)

`sprintf()`:
![image](https://user-images.githubusercontent.com/1139047/94627628-1111fa80-028c-11eb-9d7a-cd0c26a384b7.png)

The `sprintf()` function is using the `ENTER` x86 Opcode, which creates a stack frame for the current procedure of the specified size ([link](https://c9x.me/x86/html/file_module_x86_id_78.html)). I noticed that the value for the Floating Point parameter was off by one byte. When looking into the MBBSEmu implementation of `ENTER` I found:

`Registers.SP -= (ushort)(_currentInstruction.Immediate16 + 1);`

Why was it doing the `+1`? I have no idea 😕. Normally this would just make the created stack frame 1 byte larger which wasn't having adverse impact on modules (that we could tell). 

The issue here was because the `FSTP` opcode was relying on the location of the Base Pointer (`BP`) for the eventual location of the Floating Point value that was popped from `ST(0)`, it was saving the value 1 byte off from its intended location.

I'll make the change to the Opcode and Check in a Unit Test as well to verify it's setting the BP & SP values properly.
