### ISSUE TITLE
[WCCMMUD] MajorMud - Does not allow you to exit

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#200]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Does not allow you to exit

**To Reproduce**
1. Enter MajorMud module
2. (create character if none exists)
3. Enter the Realm
4. Attempt to Exit ("X")
5. See Error

**Expected behavior**
Ability to exit to menu

**Screenshots**
```
No Console errors
```
**Exit game:**
![MM1](https://user-images.githubusercontent.com/27604078/96338978-2e4e1380-1057-11eb-9d63-0c8c0c73d988.jpg)

**No ability to exit or move around or execute commands -- can hangup and reenter**
![MM2](https://user-images.githubusercontent.com/27604078/96338980-30b06d80-1057-11eb-93c3-3c90a934c6a2.jpg)

**You start game with 9 lives, when you hangup and reenter you still have 9 lives so you were never really dead**
![MM3](https://user-images.githubusercontent.com/27604078/96339030-740adc00-1057-11eb-8dbc-d0e2d2de49d5.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101620-3

**Comment by enusbaum** [comment]
Submitted a PR to fix this issue. 

The Ordinal `CURUSR` was only setting the `ChannelNumber` variable locally to the specified channel. What needs to happen is the active pointers for things like `usaprt`, `usrptr`, etc. need to be updated to specify the new channel as well. 

Additionally, we need to call `UpdateSession()` before switching to the new session in order to save items that might have been changed on those structs (`substt`, etc.)

This is why things got weird... because MajorMUD essentially thought the user was no longer logged in and cleaned up the user data. But because we weren't saving the updated `substt`, it didn't know that the user was now back at the menu.
