### ISSUE TITLE
[WCCMMUD] MajorMud - Topten Adventurers does not show name

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#204]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Topten Adventurers does not show name

**To Reproduce**
1. Enter MajorMud module
2. Select "T" Top Ten Adventurers
4. See Error

**Expected behavior**
Show names of adventurers

**Screenshots**
```
No Console Error
```

![MMTOPTEN](https://user-images.githubusercontent.com/27604078/96357105-adc1fe00-10bc-11eb-9bab-4d29a5f3f29d.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101820-1

**Comment by enusbaum** [comment]
This issue is being caused by nested `SPR` calls in MajorMUD for the Top Heroes screen. 

The current implementation of `SPR` uses a single buffer for the result, which is reused with each subsequent call (to avoid leaking memory with each call). Because of this, the player name is sent to `SPR` using the format of `%s %s`, followed by their rank using `%d`. Because they're using the same buffer, the same pointer is being returned by `SPR` and the same value is being displayed for both Rank and Name.

The fix here is probably to establish a Ring Buffer in a dedicated segment of memory for SPR and just increment the pointer/overflow back to `0x0000` when the end of the segment is reached. This would allow up to 64k of nested SPR output with unique pointers to each value.

**Comment by enusbaum** [comment]
![image](https://user-images.githubusercontent.com/1139047/98754820-7251e100-2395-11eb-851c-ccefb0401331.png)
