### ISSUE TITLE
[WCCMMUD] MajorMud - Map of Newhaven has extra Carriage Returns

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#206]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Map of Newhaven has extra Carriage Returns

**To Reproduce**
1. Enter MajorMud module
2. Create character if none exists, enter game
3. Execute "MAP" command
4. See Error

**Expected behavior**
Map displays correctly

**Screenshots**
```
No Console Error
```

![MM Map](https://user-images.githubusercontent.com/27604078/96357140-4789ab00-10bd-11eb-8789-a11f3ebcff25.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101820-1

**Comment by enusbaum** [comment]
The problem here is that the information is coming from a `.ANS` file, which already has properly formatted `\r\n` newline escapes.

When we `outprf()`, the helper method `FormatNewLineCarriageReturn` is called, which replaces any `\r\` with `\r\n` and any `\n` with `\r\n`. I'm adding code to verify that the sequence being replaced isn't already `\r\n` (or reverse order) to ensure we don't DOUBLE the new lines.

**Comment by enusbaum** [comment]
![image](https://user-images.githubusercontent.com/1139047/96473076-32b53080-11ff-11eb-9b9c-eb2311982ffa.png)

**Comment by paladine** [comment]
The fix has broken TA's `st\r\n` output

**Comment by paladine** [comment]
Maybe we want to continue the prior behavior during a `prfmsg` call but do not do the expansion in a normal `prf` write?
