### ISSUE TITLE
[WCCMMUD] Major Mud - Character Editor ANSI not lined up/garbage

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#240]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Character Editor ANSI not lined up/garbage

**To Reproduce**
1. Enter MajorMud module
2. Enter character creation
4. See Error

**Expected behavior**
FSD looks normal

**Screenshots**
```
No Console Error
```

![FSDerror](https://user-images.githubusercontent.com/27604078/97786472-c41a9000-1b79-11eb-928c-396574bf6481.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 103120-15

**Comment by enusbaum** [comment]
This was a regressed in MajorMUD caused by #234 and #235 where `\r\n` was being correctly insert into MCV string values. The FSD code was looking for `\r` to increment the Y value, so when it found the following `\n` is incremented X. 

Because with #235 the sequence for newlines from an MCV will always be `\r\n`, we increment the Y position on `\n`. 

This fixed the display issues with the MajorMUD full screen editor:

![image](https://user-images.githubusercontent.com/1139047/97786767-2b3d4200-1b84-11eb-9ef3-a4b7c2131a13.png)
