### ISSUE TITLE
Critical Exception when SoC attempts to create directory in Linux

### ISSUE THREAD

**Issue by dlightman311** [enusbaum/MBBSEmu#27]
SoC attempts to create MUICHAOS\DATA\TEXT which fails with System.IO.IOException: Invalid argument and the target directory "TEXT" is not created. This occurs under Linux using the SoC distribution from the MBBSEmu site.

![image](https://user-images.githubusercontent.com/40728931/90549683-d8471780-e15c-11ea-9bab-559e3ab171c4.png)

**Comment by enusbaum** [comment]
`FileUtility.FindFile()` will need to be enhanced/refactored to support paths that are N directories deep. 

Currently it only supports searching 1 directory deep from the module base path on case sensitive file systems, which is causing the issue here. SoC is trying to access `<base>\DATA\TEXT\` which is 2 deep.

**Comment by dlightman311** [comment]
In this test case MBBSEmu is running on a case insensitive file system (lowntfs-3g with mount options ignore_case, windows_names). Manually creating <base>\DATA\TEXT\ does not have any affect on the issue.

**Comment by dlightman311** [comment]
Confirmed working in Build #082820-3. I can create a player and enter the game more testing will be needed but this can be closed!
