### ISSUE TITLE
Selecting modules from main menu

### ISSUE THREAD

**Issue by dlightman311** [enusbaum/MBBSEmu#35]
There seems to be an input handling issue in build 081920-8. If more than 9 modules are loaded attempts to access modules with an option number of greater than 9 seem to have the second digit truncated loading module 1.

Additionally after this occurs BladeMaster and Blox are left in a inaccessible state where only the "module menu" is displayed then returning to the main menu. Restarting MBBSEmu restores access until a module > 9 is selected again. 

Captures:

[first.txt](https://github.com/enusbaum/MBBSEmu/files/5103768/first.txt)
[second.txt](https://github.com/enusbaum/MBBSEmu/files/5103776/second.txt)

**Comment by enusbaum** [comment]
What maniac would ever want to run more than 9 modules?! ;)

https://github.com/enusbaum/MBBSEmu/blob/master/MBBSEmu/HostProcess/HostRoutines/MenuRoutines.cs#L284

**Comment by fletcherm** [comment]
Started tinkering with this -- got an environment setup with a bunch of modules, reproduced the bug, and played around with what a fix might look like.

Here's a diff of what I did that got things working better
```
-            var inputValue = Encoding.ASCII.GetString(session.InputBuffer.ToArray()).ToUpper()[0];
+            var inputValue = Encoding.ASCII.GetString(session.InputBuffer.ToArray());

             //User is Logging Off
-            if (inputValue == 'X')
+            if (inputValue.ToUpper() == "X")
```

Crashes when I enter `-10` so that needs to be improved as well.

Next step: stash these changes, create some failing tests, then apply the fixes.
