### ISSUE TITLE
[NTHORDER] NTHOrder - Module fails to Initialize

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#73]
**Module Information**
* Identifier: NTHORDER
* Module Name: Warlords of Order & Chaos
* Version: unknown

**Describe the bug**
Module fails to initialize

**To Reproduce**
1. Add module to moduleConfig.json

**Expected behavior**
Module initializes

**Screenshots**
```
Critical Exception has occured:
System.ArgumentException: An item with the same key has already been added. Key: STAYCAS
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at MBBSEmu.Module.MsgFile.BuildMCV()
   at MBBSEmu.Module.MsgFile..ctor(String modulePath, String msgName)
   at MBBSEmu.Module.MbbsModule..ctor(IFileUtility fileUtility, String moduleIdentifier, String path, MemoryCore memoryCore)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: N/A

**Comment by enusbaum** [comment]
Initial issue was caused by the module having duplicate keys in the MSG file `STAYCAS`.. which is weird because it generates an invalid .H file when run through WG because it spits out two constants with the same name and different values.

I addressed this in `MsgFile.BuildMCV()` by appending a `_X` (where x it he # of duplicates) to the variable name. It's only used in this dictionary for building the resulting MCV, so the name doesn't matter much.

Once I addressed that, there were a ton of missing Ordinals related to video buffer manipulation that it does on startup (to show an `nTh` logo on the system console). Added those Ordinals (`526`, `563`, `548`, `392`, `513`) and also added a couple new Ordinals (`701` printf(), `314` gen_haskey()) and was able to get the game to init and enter:

![image](https://user-images.githubusercontent.com/1139047/92156683-5b23cf80-edf7-11ea-9fef-437c45700539.png)

Still missing APIs when creating a new character, working on those now.
